$(()=>{
    $(".active").mousemove(()=>{
        $(".al").css({
            display:"block"
        })
    })
    $(".active").mouseleave(()=>{
        $(".al").css({
            display:"none"
        })
    })    
    $(".two").mousemove(()=>{
        $(".two_box").css({
            display:"block",
        })
        $(".two").css({color:"red",
        background:"white"})
    })
    $(".two").mouseleave(()=>{
        $(".two_box").css({
            display:"none"
        })
        $(".two").css({
            color:"white",
        background:"red"})
    })
    $(".tWo").mousemove(()=>{
        $(".two_Box").css({
            display:"block",
        })
        $(".tWo").css({color:"red",
        background:"white"})
    })
    $(".tWo").mouseleave(()=>{
        $(".two_Box").css({
            display:"none"
        })
        $(".tWo").css({
            color:"white",
        background:"red"
    })
    })
    $(".twO").mousemove(()=>{
        $(".two_bOx").css({
            display:"block",
        })
        $(".twO").css({color:"red",
        background:"white"})
    })
    $(".twO").mouseleave(()=>{
        $(".two_bOx").css({
            display:"none"
        })
        $(".twO").css({
            color:"white",
        background:"red"
    })
    })
    $(".Two").mousemove(()=>{
        $(".two_boX").css({
            display:"block"
        })
        $(".Two").css({color:"red",
        background:"white"})
    })
    $(".Two").mouseleave(()=>{
        $(".two_boX").css({
            display:"none"
        })
        $(".Two").css({
            color:"white",
        background:"red"
    })
    })
    $(".TWo").mousemove(()=>{
        $(".two_BOx").css({
            display:"block"
        })
        $(".TWo").css({color:"red",
        background:"white"})
    })
    $(".TWo").mouseleave(()=>{
        $(".two_BOx").css({
            display:"none"
        })
        $(".TWo").css({
            color:"white",
        background:"red"
    })
    })
    $(".TWO").mousemove(()=>{
        $(".two_BOX").css({
            display:"block",
        })
        $(".TWO").css({
            color:"red",
        background:"white"})
    })
    $(".TWO").mouseleave(()=>{
        $(".two_BOX").css({
            display:"none"
        })
        $(".TWO").css({
            color:"white",
        background:"red"
    })
    })
    $(".twoo").mousemove(()=>{
        $(".twoo").css({
            color:"red",
        background:"white"})
    })
    $(".twoo").mouseleave(()=>{
        $(".twoo").css({
            color:"white",
        background:"red"
    })
    })
    $(".sign").mousemove(()=>{
        $(".sign").css({
            color:"red"
        })
    })
    $(".sign").mouseleave(()=>{
        $(".sign").css({
            color:"black"
        })
    })
    $(".register").mousedown(()=>{
       location.href("register.html");
    })
    $(".register").mousemove(()=>{
        $(".register").css({
            color:"red"
        })
    })
    $(".register").mouseleave(()=>{
        $(".register").css({
            color:"black"
        })
    })
})